services:
  api:
    container_name: "home-finance-api"
    build: ./home-finance-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/home-finance
      DATABASE_USER: local
      DATABASE_PASSWORD: local
  database:
    container_name: home-finance-database
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: local
      POSTGRES_DB: home-finance
